# Generated by Django 4.0 on 2022-01-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certification',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='my_education',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='my_experience',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
